#!/usr/bin/env python
# encoding: utf-8
"""
script.py

Created by mark henderson on 2013-02-19.
Copyright (c) 2013 __MyCompanyName__. All rights reserved.
"""
from util import add, connect

#create the main node
meetup = add(name='meetup')


#add everyone 
mark = add(name='mark')
patrick = add(name='patrick')
greg = add(name='greg')
joel = add(name='joel')
leila = add(name='leila')
howard = add(name='howard')
henry = add(name='henry')
brandon = add(name='brandon')
chris = add(name='chris')
kevin = add(name='kevin')
will = add(name='will')
mike = add(name='mike')
kathleen = add(name='kathleen')
foster = add(name='foster')
jeff = add(name='jeff')
matt = add(name='matt')
david = add(name='david')
vijay = add(name='vijay')
paul = add(name='paul')
brian = add(name='brian')
hogan = add(name='hogan')
matthew = add(name='matthew')
zac = add(name='zac')
russ = add(name='russ')
eric = add(name='eric')
vlad = add(name='vlad')
#add things

gui = add(name='gui')
converge = add(name='converge')
dc = add(name='dc')
entreprenurship = add(name='entrepreneurship')
women = add(name='women')
sgt = add(name='sgt')
python = add(name='python')
php = add(name='php')
js = add(name='javascript')
pizza = add(name='pizza')
beer = add(name='beer')
cleaning = add(name='cleaning')
interning = add(name='interning')
tps = add(name='tps')
afsheen = add(name='afsheen')
starcraft = add(name='starcraft')
starcraft2 = add(name='starcraft2')
pancakes = add(name='pancakes')
waffles = add(name='waffles')
liver = add(name='liver')
homebrew = add(name='homebrew')
documentation = add(name='documentation')
cold = add(name='the cold')
snakes = add(name='snakes')
money = add(name='money')
yankees = add(name='yankees')
nothing = add(name='nothing')
cigs = add(name='cigs')
pennies = add(name='pennies')
tennis = add(name='tennis')

#add what people like
connect(zac, beer, 'likes')
connect(afsheen, cigs, 'likes')
connect(afsheen, zac, 'dislikes')
connect(afsheen, pennies, 'dislikes')
connect(zac, afsheen, 'dislikes')
connect(vlad, beer, 'likes')
connect(vlad, cleaning, 'likes')
connect(cleaning, brian, 'likes')
connect(zac, sgt, 'likes')
connect(brian, starcraft, 'likes')
connect(brian, starcraft2, 'dislikes')
connect(hogan, dc, 'likes')
connect(paul, sgt, 'works')
connect(paul, sgt, 'likes')
connect(paul, cleaning, 'dislikes')
connect(patrick, sgt, 'works')
connect(patrick, sgt, 'likes')
connect(brian, sgt, 'works')
connect(brian, sgt, 'likes')
connect(meetup, python, 'likes')
connect(meetup, beer, 'likes')
connect(meetup, patrick, 'organizer')
connect(patrick, brian, 'likes')
connect(cleaning, patrick, 'likes')
connect(mike, cleaning, 'likes')
connect(mike, kathleen, 'married')
connect(mike, kathleen, 'likes')
connect(kathleen, cleaning, 'likes')
connect(kathleen, women, 'likes')
connect(mark, python, 'likes')
connect(mark, php, 'likes')
connect(mark, js, 'likes')
connect(kevin, interning, 'dislikes')
connect(kevin, converge, 'likes')
connect(brian, sgt, 'works')
connect(kevin, php, 'likes')
connect(jeff, php, 'likes')
connect(jeff, yankees, 'dislikes')
connect(mark, documentation, 'likes')
connect(vijay, python, 'likes')
connect(vijay, documentation, 'dislikes')
connect(matthew, entreprenurship, 'likes')
connect(matthew, python, 'likes')
connect(matthew, cold, 'dislikes')
connect(foster, python, 'likes')
connect(foster, tps, 'dislikes')
connect(zac, foster, 'likes')
connect(foster, afsheen, 'dislikes')
connect(foster, starcraft, 'works')
connect(hogan, pancakes, 'likes')
connect(hogan, waffles, 'dislikes')
connect(russ, homebrew, 'likes')
connect(russ, liver, 'dislikes')
connect(leila, money, 'likes')
connect(leila, snakes, 'dislikes')
connect(eric, women, 'likes')
connect(eric, women, 'dislikes')
connect(joel, python, 'likes')
connect(joel, snakes, 'likes')
connect(joel, waffles, 'likes')
connect(joel, nothing, 'dislikes')
connect(howard, tennis, 'likes')
connect(howard, cigs, 'dislikes')
